<a href="https://colab.research.google.com/github/Rifal737/Pemrograman-web/blob/main/Big_data_saham.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Big Data dengan Dataset Saham Antam**
Nama : Muhamad Rifal
Nim : 24.11.6082

**dari github**

In [ ]:
 # import library
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib as mpl
import matplotlib.pyplot as plt

In [ ]:
#Menampilkan dataset Saham ANTM
df=pd.read_csv("ANTM.JK.csv",encoding='latin1')
df.head(20)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2005-09-29,432.588074,436.787964,407.388763,432.588074,304.904572,76180670.0
1,2005-09-30,457.787384,457.787384,432.588074,457.787384,322.666016,105493978.0
2,2005-10-03,470.387024,474.586914,440.987854,470.387024,331.546692,59712955.0
3,2005-10-04,474.586914,482.986694,466.187164,474.586914,334.506927,56236668.0
4,2005-10-05,482.986694,482.986694,466.187164,482.986694,340.427429,31319315.0
5,2005-10-06,466.187164,482.986694,461.987274,466.187164,328.586487,8107366.0
6,2005-10-07,470.387024,470.387024,457.787384,470.387024,331.546692,6577562.0
7,2005-10-10,466.187164,470.387024,457.787384,466.187164,328.586487,23223854.0
8,2005-10-11,466.187164,466.187164,461.987274,466.187164,328.586487,13497395.0
9,2005-10-12,470.387024,474.586914,466.187164,470.387024,331.546692,29804392.0
10,2005-10-13,474.586914,474.586914,470.387024,474.586914,334.506927,12738446.0
11,2005-10-14,474.586914,474.586914,470.387024,474.586914,334.506927,12018188.0
12,2005-10-17,474.586914,474.586914,474.586914,474.586914,334.506927,0.0
13,2005-10-18,470.387024,474.586914,470.387024,470.387024,331.546692,12110452.0
14,2005-10-19,461.987274,470.387024,461.987274,461.987274,325.626251,5631107.0
15,2005-10-20,461.987274,461.987274,461.987274,461.987274,325.626251,0.0
16,2005-10-21,461.987274,461.987274,461.987274,461.987274,325.626251,3038774.0
17,2005-10-24,449.387604,461.987274,445.187744,449.387604,316.745544,10875299.0
18,2005-10-25,449.387604,449.387604,449.387604,449.387604,316.745544,0.0
19,2005-10-26,453.587494,457.787384,449.387604,453.587494,319.705750,14298013.0

In [ ]:
#Melihat stuktur dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3808 entries, 0 to 3807
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3808 non-null   object
 1   Open       3807 non-null   float64
 2   High       3807 non-null   float64
 3   Low        3807 non-null   float64
 4   Close      3807 non-null   float64
 5   Adj Close  3807 non-null   float64
 6   Volume     3807 non-null   float64
dtypes: float64(6), object(1)
memory usage: 208.4+ KB

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [ ]:
df.shape

(3808, 7)

**cara 2 upload data dari google drive (link path)**

In [ ]:
from google.colab import drive
drive.mount('/content/ANTM.JK.csv')

Mounted at /content/ANTM.JK.csv

In [ ]:
df = pd.read_csv('/content/ANTM.JK.csv/MyDrive/Big Data/ANTM.JK.csv')
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2005-09-29,432.588074,436.787964,407.388763,432.588074,304.904572,76180670.0
1,2005-09-30,457.787384,457.787384,432.588074,457.787384,322.666016,105493978.0
2,2005-10-03,470.387024,474.586914,440.987854,470.387024,331.546692,59712955.0
3,2005-10-04,474.586914,482.986694,466.187164,474.586914,334.506927,56236668.0
4,2005-10-05,482.986694,482.986694,466.187164,482.986694,340.427429,31319315.0
5,2005-10-06,466.187164,482.986694,461.987274,466.187164,328.586487,8107366.0
6,2005-10-07,470.387024,470.387024,457.787384,470.387024,331.546692,6577562.0
7,2005-10-10,466.187164,470.387024,457.787384,466.187164,328.586487,23223854.0
8,2005-10-11,466.187164,466.187164,461.987274,466.187164,328.586487,13497395.0
9,2005-10-12,470.387024,474.586914,466.187164,470.387024,331.546692,29804392.0